baseURL: "https://adithyaakrishna.github.io/"
title: Adithya's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Adithya's Blog
  description: "My Personal Blog"
  keywords: [Blog, Portfolio, PaperMod, Adi, AdiKris, Red Hat]
  author: Adithya Krishna
  images: ["https://avatars.githubusercontent.com/u/23498248?v=4"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  disableHLJS: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/logo.png"
    favicon16x16: "/logo.png"
    favicon32x32: "logo.png"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Adithya Krishna"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hello \U0001F44B"
    Content: > 
      - I am an Associate Software Engineer at [Red Hat](https://www.redhat.com), where I work with tools/libraries like ReactJS, NodeJS, Storybook, Patternfly(Red Hat's Design System), Lerna (monorepo manager), GitLab and it's Pipelines. I also work on AdobeXd and Figma designs to keep the creative part of me alive.
      
      - 

      - Maintainer (Docs) of [Meshery](https://github.com/meshery) (a CNCF Sandbox Project), where I contribute quite oftenly in areas of UI, GitHub Actions, documentation updates, reviewing PRs and suggesting improvements.
      
      -
      
      - A MeshMate at [Layer5](https://layer5.io), where I help new contributors get started with open-source, help them contribute to [Meshery](https://github.com/meshery), have regular sync-ups with new community members to set-up their local dev environments while contributing to Meshery or Layer5 projects.
      
      -
      
      - Apart from work, I love contributing to open-source, reading blogs/newsletters related to tech and latest trends in it. I also love participating in hackathons and during the past two years, I have won in a couple of them as well [My hackathon Projects](http://bit.ly/adikris-hackathons)

  socialIcons:
    - name: twitter
      url: "https://twitter.com/adii_kris"
    - name: github
      url: "https://github.com/adithyaakrishna"
    - name: linkedin
      url: "https://www.linkedin.com/in/navendup/"
    - name: dev
      url: "https://dev.to/adithyaakrishna"
    - name: snapchat
      url: "https://snapchat.com/add/adi.kris"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/adithyaakrishna/blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # For Search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: twitter
      name: Twitter
      url: https://twitter.com/adii_kris
      weight: 30
    - identifier: github
      name: GitHub
      url: https://github.com/adithyaakrishna
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: github
